package View;

import Controller.GerenciarEstoqueController;
import Model.Academia;
import Model.Produto;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class AdicionarProduto extends javax.swing.JFrame {

    private Academia academia;
    
    private final GerenciarEstoqueController controller;
    
    /**
     * Creates new form AdcionarProduto
     * @param academia
     * @param controller
     */
    public AdicionarProduto(Academia academia, GerenciarEstoqueController controller) {
        initComponents();
        this.academia = academia;
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextVCompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextVVenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Adicionar Produto");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Adicionar Produto");

        jLabel2.setText("Nome:");

        jTextNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomeKeyPressed(evt);
            }
        });

        jTextDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextDescricaoKeyPressed(evt);
            }
        });

        jLabel3.setText("Descrição:");

        jTextQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextQuantidadeKeyPressed(evt);
            }
        });

        jLabel4.setText("Quantidade:");

        jTextVCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextVCompraKeyPressed(evt);
            }
        });

        jLabel5.setText("Valor de compra:");

        jTextVVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextVVendaKeyPressed(evt);
            }
        });

        jLabel6.setText("Valor de venda:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Adicionar Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNome)
                        .addComponent(jTextDescricao)
                        .addComponent(jTextQuantidade))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jTextVCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jTextVVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextVCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextVVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextDescricao.requestFocus();
        }
    }//GEN-LAST:event_jTextNomeKeyPressed

    private void jTextDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDescricaoKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextQuantidade.requestFocus();
        }
    }//GEN-LAST:event_jTextDescricaoKeyPressed

    private void jTextQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextQuantidadeKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextVCompra.requestFocus();
        }
    }//GEN-LAST:event_jTextQuantidadeKeyPressed

    private void jTextVCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextVCompraKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextVVenda.requestFocus();
        }
    }//GEN-LAST:event_jTextVCompraKeyPressed

    private void jTextVVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextVVendaKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jTextVVendaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int quantidade = Integer.parseInt(jTextQuantidade.getText());
        float valorCompra = Float.parseFloat(jTextVCompra.getText());
        float valorVenda = Float.parseFloat(jTextVVenda.getText());
        Produto produto = new Produto(
                jTextNome.getText(), 
                jTextDescricao.getText(),
                quantidade,
                valorCompra,
                valorVenda
        );
        if(controller.buscarProduto(jTextNome.getText()) == null){
            controller.adicionarProduto(produto);
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
            limparCampos();
        } else{
            JOptionPane.showMessageDialog(null, "Produto já existente!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        /**
         * Cadastra aluno com o ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int quantidade = Integer.parseInt(jTextQuantidade.getText());
            float valorCompra = Float.parseFloat(jTextVCompra.getText());
            float valorVenda = Float.parseFloat(jTextVVenda.getText());
            Produto produto = new Produto(
                    jTextNome.getText(), 
                    jTextDescricao.getText(),
                    quantidade,
                    valorCompra,
                    valorVenda
            );
            if(controller.buscarProduto(jTextNome.getText()) == null){
                controller.adicionarProduto(produto);
                JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
                limparCampos();
            } else{
                JOptionPane.showMessageDialog(null, "Produto já existente!");
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextDescricao;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextQuantidade;
    private javax.swing.JTextField jTextVCompra;
    private javax.swing.JTextField jTextVVenda;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTextDescricao
     */
    public javax.swing.JTextField getjTextDescricao() {
        return jTextDescricao;
    }

    /**
     * @param jTextDescricao the jTextDescricao to set
     */
    public void setjTextDescricao(String jTextDescricao) {
        this.jTextDescricao.setText(jTextDescricao);
    }

    /**
     * @return the jTextNome
     */
    public javax.swing.JTextField getjTextNome() {
        return jTextNome;
    }

    /**
     * @param jTextNome the jTextNome to set
     */
    public void setjTextNome(String jTextNome) {
        this.jTextNome.setText(jTextNome);
    }

    /**
     * @return the jTextQuantidade
     */
    public javax.swing.JTextField getjTextQuantidade() {
        return jTextQuantidade;
    }

    /**
     * @param jTextQuantidade the jTextQuantidade to set
     */
    public void setjTextQuantidade(String jTextQuantidade) {
        this.jTextQuantidade.setText(jTextQuantidade);
    }

    /**
     * @return the jTextVCompra
     */
    public javax.swing.JTextField getjTextVCompra() {
        return jTextVCompra;
    }

    /**
     * @param jTextVCompra the jTextVCompra to set
     */
    public void setjTextVCompra(String jTextVCompra) {
        this.jTextVCompra.setText(jTextVCompra);
    }

    /**
     * @return the jTextVVenda
     */
    public javax.swing.JTextField getjTextVVenda() {
        return jTextVVenda;
    }

    /**
     * @param jTextVVenda the jTextVVenda to set
     */
    public void setjTextVVenda(String jTextVVenda) {
        this.jTextVVenda.setText(jTextVVenda);
    }

    /**
     * Método que limpa campos da view de estoque
     */
    public void limparCampos(){
        setjTextNome("");
        setjTextDescricao("");
        setjTextQuantidade("");
        setjTextVCompra("");
        setjTextVVenda("");
    }
}
