package View;

import Controller.GerenciarFuncionarioController;
import Model.Funcionario;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class EditarFuncionario extends javax.swing.JFrame {
    
    private final GerenciarFuncionarioController controller;
            
    private String id;
    private String nome;
    private String sobrenome;
    private String cpf;
    private String endereco;
    private String telefone;
    private String email;
    private String usuario;
    private String senha;
    private String salario;
    private String cargo;
    
    /**
     * Creates new form EditarFuncionario
     * @param id
     * @param nome
     * @param sobrenome
     * @param cpf
     * @param endereco
     * @param telefone
     * @param email
     * @param usuario
     * @param senha
     * @param salario
     * @param cargo
     */
    public EditarFuncionario(String id, String nome, String sobrenome, String cpf, String endereco, String telefone, String email, String usuario, String senha, String salario, String cargo, GerenciarFuncionarioController controller) {
        initComponents();
        this.controller = controller;
        this.id = id;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.cpf = cpf;
        this.endereco = endereco;
        this.telefone = telefone;
        this.email = email;
        this.usuario = usuario;
        this.senha = senha;
        this.salario = salario;
        this.cargo = cargo;
        
        preencherCampos(nome, sobrenome, cpf, endereco, telefone, email, usuario, senha, salario, cargo);
    }
    
    public EditarFuncionario() {
        initComponents();
        controller = null;
        this.id = null;
        this.nome = null;
        this.sobrenome = null;
        this.cpf = null;
        this.endereco = null;
        this.telefone = null;
        this.email = null;
        this.usuario = null;
        this.senha = null;
        this.salario = null;
        this.cargo = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelPessoal = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabelSobrenome = new javax.swing.JLabel();
        jTextSobrenome = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jTextCPF = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jTextEndereco = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextTelefone = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jPanelComercial = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jFieldSenha = new javax.swing.JPasswordField();
        jLabelCargo = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jLabelSalario = new javax.swing.JLabel();
        jTextSalario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Funcionário");
        setResizable(false);
        setSize(new java.awt.Dimension(434, 531));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitulo.setText("Editar Funcionário");

        jPanelPessoal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "   DADOS PESSOAIS   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        jPanelPessoal.setName(""); // NOI18N

        jLabelNome.setText("Nome:");

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });
        jTextNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomeKeyPressed(evt);
            }
        });

        jLabelSobrenome.setText("Sobrenome:");

        jTextSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSobrenomeActionPerformed(evt);
            }
        });
        jTextSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSobrenomeKeyPressed(evt);
            }
        });

        jLabelCPF.setText("CPF:");

        jTextCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCPFActionPerformed(evt);
            }
        });
        jTextCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCPFKeyPressed(evt);
            }
        });

        jLabelEndereco.setText("Endereço:");

        jTextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEnderecoActionPerformed(evt);
            }
        });
        jTextEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEnderecoKeyPressed(evt);
            }
        });

        jLabelTelefone.setText("Telefone:");

        jTextTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefoneActionPerformed(evt);
            }
        });
        jTextTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextTelefoneKeyPressed(evt);
            }
        });

        jLabelEmail.setText("Email:");

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });
        jTextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEmailKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPessoalLayout = new javax.swing.GroupLayout(jPanelPessoal);
        jPanelPessoal.setLayout(jPanelPessoalLayout);
        jPanelPessoalLayout.setHorizontalGroup(
            jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPessoalLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEndereco)
                    .addGroup(jPanelPessoalLayout.createSequentialGroup()
                        .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSobrenome)
                            .addComponent(jTextSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPessoalLayout.createSequentialGroup()
                        .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextEmail)))
                    .addComponent(jTextEndereco))
                .addGap(40, 40, 40))
        );
        jPanelPessoalLayout.setVerticalGroup(
            jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPessoalLayout.createSequentialGroup()
                        .addComponent(jLabelCPF)
                        .addGap(6, 6, 6)
                        .addComponent(jTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPessoalLayout.createSequentialGroup()
                        .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelSobrenome))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEndereco)
                .addGap(6, 6, 6)
                .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelEmail))
                .addGap(6, 6, 6)
                .addGroup(jPanelPessoalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelComercial.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "   DADOS COMERCIAIS   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N

        jLabelUsuario.setText("Usuário");

        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });
        jTextUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextUsuarioKeyPressed(evt);
            }
        });

        jLabelSenha.setText("Senha:");

        jFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldSenhaActionPerformed(evt);
            }
        });
        jFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFieldSenhaKeyPressed(evt);
            }
        });

        jLabelCargo.setText("Cargo:");

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colaborador", "Administrador" }));
        jComboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCargoActionPerformed(evt);
            }
        });

        jLabelSalario.setText("Salário:");

        jTextSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSalarioActionPerformed(evt);
            }
        });
        jTextSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSalarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComercialLayout = new javax.swing.GroupLayout(jPanelComercial);
        jPanelComercial.setLayout(jPanelComercialLayout);
        jPanelComercialLayout.setHorizontalGroup(
            jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComercialLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenha))
                .addGap(18, 18, 18)
                .addGroup(jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalario)
                    .addComponent(jTextSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCargo)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComercialLayout.setVerticalGroup(
            jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComercialLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelComercialLayout.createSequentialGroup()
                        .addComponent(jLabelSalario)
                        .addGap(45, 45, 45))
                    .addGroup(jPanelComercialLayout.createSequentialGroup()
                        .addComponent(jLabelCargo)
                        .addGap(23, 23, 23)
                        .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelComercialLayout.createSequentialGroup()
                        .addGroup(jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelSenha))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("SALVAR ALTERAÇÃO");
        jButton1.setAlignmentX(0.5F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelPessoal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelComercial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanelPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jTextNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeKeyPressed
        // TODO add your handling code here:
        /**
        * Altera o campo a partir do ENTER
        */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextSobrenome.requestFocus();
        }
    }//GEN-LAST:event_jTextNomeKeyPressed

    private void jTextSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSobrenomeActionPerformed

    private void jTextSobrenomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSobrenomeKeyPressed
        // TODO add your handling code here:
        /**
        * Altera o campo a partir do ENTER
        */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextCPF.requestFocus();
        }
    }//GEN-LAST:event_jTextSobrenomeKeyPressed

    private void jTextCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCPFActionPerformed

    private void jTextCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCPFKeyPressed
        // TODO add your handling code here:
        /**
        * Altera o campo a partir do ENTER
        */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextEndereco.requestFocus();
        }
    }//GEN-LAST:event_jTextCPFKeyPressed

    private void jTextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEnderecoActionPerformed

    private void jTextEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEnderecoKeyPressed
        // TODO add your handling code here:
        /**
        * Altera o campo a partir do ENTER
        */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextTelefone.requestFocus();
        }
    }//GEN-LAST:event_jTextEnderecoKeyPressed

    private void jTextTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefoneActionPerformed

    private void jTextTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefoneKeyPressed
        // TODO add your handling code here:
        /**
        * Altera o campo a partir do ENTER
        */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextEmail.requestFocus();
        }
    }//GEN-LAST:event_jTextTelefoneKeyPressed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailKeyPressed
        // TODO add your handling code here:
        /**
        * Altera o campo a partir do ENTER
        */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextUsuario.requestFocus();
        }
    }//GEN-LAST:event_jTextEmailKeyPressed

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void jTextUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUsuarioKeyPressed
        // TODO add your handling code here:
        /**
        * Altera o campo a partir do ENTER
        */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jFieldSenha.requestFocus();
        }
    }//GEN-LAST:event_jTextUsuarioKeyPressed

    private void jFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldSenhaActionPerformed

    private void jFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldSenhaKeyPressed
        // TODO add your handling code here:
        /**
        * Altera o campo a partir do ENTER
        */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextSalario.requestFocus();
        }
    }//GEN-LAST:event_jFieldSenhaKeyPressed

    private void jComboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCargoActionPerformed

    private void jTextSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSalarioActionPerformed

    private void jTextSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSalarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSalarioKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String senha = new String(jFieldSenha.getPassword());
        float salario = Float.parseFloat(jTextSalario.getText());
        String cargo = (String) jComboBoxCargo.getSelectedItem();
        Funcionario funcionarioAtualizado = new Funcionario(
                cargo,
                salario,
                jTextUsuario.getText(),
                senha,
                jTextNome.getText(), 
                jTextSobrenome.getText(),
                jTextCPF.getText(), 
                jTextEndereco.getText(), 
                jTextTelefone.getText(), 
                jTextEmail.getText()
        );
        if(controller.editarFuncionario(cpf, funcionarioAtualizado)){
            JOptionPane.showMessageDialog(null, "Funcionario editado com sucesso!");
        } else{
            JOptionPane.showMessageDialog(null, "Não foi possivel editar o funcionario!");
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JPasswordField jFieldSenha;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelComercial;
    private javax.swing.JPanel jPanelPessoal;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSalario;
    private javax.swing.JTextField jTextSobrenome;
    private javax.swing.JTextField jTextTelefone;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables

    public String getId(){
        return id;
    }
    
    public JPasswordField getjFieldSenha() {
        return jFieldSenha;
    }

    public void setjFieldSenha(String jFieldSenha) {
        this.jFieldSenha.setText(jFieldSenha);
    }

    public JTextField getjTextCPF() {
        return jTextCPF;
    }

    public void setjTextCPF(String jTextCPF) {
        this.jTextCPF.setText(jTextCPF);
    }

    public JTextField getjTextEmail() {
        return jTextEmail;
    }

    public void setjTextEmail(String jTextEmail) {
        this.jTextEmail.setText(jTextEmail);
    }

    public JTextField getjTextEndereco() {
        return jTextEndereco;
    }

    public void setjTextEndereco(String jTextEndereco) {
        this.jTextEndereco.setText(jTextEndereco);
    }

    public JTextField getjTextNome() {
        return jTextNome;
    }

    public void setjTextNome(String jTextNome) {
        this.jTextNome.setText(jTextNome);
    }

    public JTextField getjTextSalario() {
        return jTextSalario;
    }

    public void setjTextSalario(String jTextSalario) {
        this.jTextSalario.setText(jTextSalario);
    }

    public JTextField getjTextSobrenome() {
        return jTextSobrenome;
    }

    public void setjTextSobrenome(String jTextSobrenome) {
        this.jTextSobrenome.setText(jTextSobrenome);
    }

    public JTextField getjTextTelefone() {
        return jTextTelefone;
    }

    public void setjTextTelefone(String jTextTelefone) {
        this.jTextTelefone.setText(jTextTelefone);
    }

    public JTextField getjTextUsuario() {
        return jTextUsuario;
    }

    public void setjTextUsuario(String jTextUsuario) {
        this.jTextUsuario.setText(jTextUsuario);
    }

    public void setjComboBoxCargo(String cargo) {
        if("Colaborador".equals(cargo)){
            this.jComboBoxCargo.setSelectedIndex(0);
        }else{
            this.jComboBoxCargo.setSelectedIndex(1);
        }
    }

    public JComboBox<String> getjComboBoxCargo() {
        return jComboBoxCargo;
    }
    
    public void preencherCampos(String nome, String sobrenome, String cpf, String endereco, String telefone, String email, String usuario, String senha, String salario, String cargo){
        setjTextNome(nome);
        setjTextSobrenome(sobrenome);
        setjTextCPF(cpf);
        setjTextEndereco(endereco);
        setjTextTelefone(telefone);
        setjTextEmail(email);
        setjTextUsuario(usuario);
        setjFieldSenha(senha);
        setjTextSalario(salario);
        setjComboBoxCargo(cargo);
    }
    
    @Override
    public String toString(){
        return "View de EditarFuncionario";
    }
}
