package View;

import Controller.GerenciarAlunoController;
import Model.Aluno;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class EditarAluno extends javax.swing.JFrame {

    private GerenciarAlunoController controller;

    private String id;
    private String nome;
    private String sobrenome;
    private String cpf;
    private String endereco;
    private String telefone;
    private String email;
    private String cartao;
    
    public EditarAluno(String id, String nome, String sobrenome, String cpf, String endereco, String telefone, String email, String cartao, GerenciarAlunoController controller) {
        initComponents();
        this.controller = controller;
        this.id = id;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.cpf = cpf;
        this.endereco = endereco;
        this.telefone = telefone;
        this.email = email;
        this.cartao = cartao;
        
        preencherCampos(nome, sobrenome, cpf, endereco, telefone, email, cartao);
    }
    
    public EditarAluno() {
        initComponents();
        controller = null;
        this.id = null;
        this.nome = null;
        this.sobrenome = null;
        this.cpf = null;
        this.endereco = null;
        this.telefone = null;
        this.email = null;
        this.cartao = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextSobrenome = new javax.swing.JTextField();
        jTextCPF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextEndereco = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextTelefone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextCartao = new javax.swing.JTextField();
        jLabelSubtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Aluno");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitulo.setText("Editar Aluno");

        jNome.setText("Nome:");

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });
        jTextNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomeKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Salvar Alterações");
        jButton1.setAlignmentX(0.5F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel15.setText("Sobrenome:");

        jTextSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSobrenomeActionPerformed(evt);
            }
        });
        jTextSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSobrenomeKeyPressed(evt);
            }
        });

        jTextCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCPFActionPerformed(evt);
            }
        });
        jTextCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCPFKeyPressed(evt);
            }
        });

        jLabel16.setText("CPF:");

        jLabel17.setText("Endereço:");

        jTextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEnderecoActionPerformed(evt);
            }
        });
        jTextEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEnderecoKeyPressed(evt);
            }
        });

        jLabel18.setText("Telefone:");

        jTextTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefoneActionPerformed(evt);
            }
        });
        jTextTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextTelefoneKeyPressed(evt);
            }
        });

        jLabel19.setText("Email:");

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });
        jTextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextEmailKeyPressed(evt);
            }
        });

        jLabel20.setText("Cartão:");

        jTextCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCartaoActionPerformed(evt);
            }
        });
        jTextCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCartaoKeyPressed(evt);
            }
        });

        jLabelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSubtitulo.setText("Atualize os dados do aluno nos campos abaixo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCartao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextCPF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addComponent(jTextEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubtitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Aluno alunoAtualizado = new Aluno(
                jTextNome.getText(), 
                jTextSobrenome.getText(),
                jTextCPF.getText(), 
                jTextEndereco.getText(), 
                jTextTelefone.getText(), 
                jTextEmail.getText(), 
                jTextCartao.getText());
                        
        if(controller.editarAluno(cpf, alunoAtualizado)){
            JOptionPane.showMessageDialog(null, "Aluno editado com sucesso!");
        } else{
            JOptionPane.showMessageDialog(null, "Não foi possivel editar o aluno!");
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSobrenomeActionPerformed

    private void jTextCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCPFActionPerformed

    private void jTextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEnderecoActionPerformed

    private void jTextTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefoneActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCartaoActionPerformed

    private void jTextNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextSobrenome.requestFocus();
        }
    }//GEN-LAST:event_jTextNomeKeyPressed

    private void jTextSobrenomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSobrenomeKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextCPF.requestFocus();
        }
    }//GEN-LAST:event_jTextSobrenomeKeyPressed

    private void jTextCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCPFKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextEndereco.requestFocus();
        }
    }//GEN-LAST:event_jTextCPFKeyPressed

    private void jTextEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEnderecoKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextTelefone.requestFocus();
        }
    }//GEN-LAST:event_jTextEnderecoKeyPressed

    private void jTextTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefoneKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextEmail.requestFocus();
        }
    }//GEN-LAST:event_jTextTelefoneKeyPressed

    private void jTextEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTextCartao.requestFocus();
        }
    }//GEN-LAST:event_jTextEmailKeyPressed

    private void jTextCartaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCartaoKeyPressed
        // TODO add your handling code here:
        /**
         * Altera o campo a partir do ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jTextCartaoKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        /**
         * Salvar alterações do aluno com o ENTER
         */
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Aluno alunoAtualizado = new Aluno(
                jTextNome.getText(), 
                jTextSobrenome.getText(),
                jTextCPF.getText(), 
                jTextEndereco.getText(), 
                jTextTelefone.getText(), 
                jTextEmail.getText(), 
                jTextCartao.getText());
                        
        if(controller.editarAluno(cpf, alunoAtualizado)){
            JOptionPane.showMessageDialog(null, "Aluno editado com sucesso!");
        } else{
            JOptionPane.showMessageDialog(null, "Não foi possivel editar o aluno!");
        }
        dispose();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jNome;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextCartao;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSobrenome;
    private javax.swing.JTextField jTextTelefone;
    // End of variables declaration//GEN-END:variables

    

    /**
     * Get Nome
     * @return nome
     */
    public JTextField getjTextNome() {
        return jTextNome;
    }

    /**
     * Set nome
     * @param jTextNome 
     */
    public void setjTextNome(String jTextNome) {
        this.jTextNome.setText(jTextNome);
    }

    /**
     * Get Sobrenome
     * @return sobrenome
     */
    public JTextField getjTextSobrenome() {
        return jTextSobrenome;
    }

    /**
     * Set sobrenome
     * @param jTextSobrenome 
     */
    public void setjTextSobrenome(String jTextSobrenome) {
        this.jTextSobrenome.setText(jTextSobrenome);
    }
    
    /**
     * Get CPF
     * @return CPF
     */
    public JTextField getjTextCPF() {
        return jTextCPF;
    }

    /**
     * Set CPF
     * @param jTextCPF 
     */
    public void setjTextCPF(String jTextCPF) {
        this.jTextCPF.setText(jTextCPF);
    }
    
    /**
     * Get Endereço
     * @return endereço
     */
    public JTextField getjTextEndereco() {
        return jTextEndereco;
    }

    /**
     * Set endereço
     * @param jTextEndereco 
     */
    public void setjTextEndereco(String jTextEndereco) {
        this.jTextEndereco.setText(jTextEndereco);
    }

    /**
     * Get telefone
     * @return 
     */
    public JTextField getjTextTelefone() {
        return jTextTelefone;
    }

    /**
     * Set telefone
     * @param jTextTelefone 
     */
    public void setjTextTelefone(String jTextTelefone) {
        this.jTextTelefone.setText(jTextTelefone);
    }
    
    /**
     * Get email
     * @return email
     */
    public JTextField getjTextEmail() {
        return jTextEmail;
    }

    /**
     * Set email
     * @param jTextEmail 
     */
    public void setjTextEmail(String jTextEmail) {
        this.jTextEmail.setText(jTextEmail);
    }
    
    /**
     * Get cartão
     * @return cartão
     */
    public JTextField getjTextCartao() {
        return jTextCartao;
    }

    /**
     * Set cartão 
     * @param cartao
     */
    public void setjTextCartao(String cartao){
        this.jTextCartao.setText(cartao);
    }

    /**
     * @return the id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }
    
    public void preencherCampos(String nome, String sobrenome, String cpf, String endereco, String telefone, String email, String cartao){
        setjTextNome(nome);
        setjTextSobrenome(sobrenome);
        setjTextCPF(cpf);
        setjTextEndereco(endereco);
        setjTextTelefone(telefone);
        setjTextEmail(email);
        setjTextCartao(cartao);
    }
    
    @Override
    public String toString(){
        return "View de EditarAluno";
    }
}
