package View;

import Controller.AgendamentoController;
import Controller.CatracaController;
import Controller.GerenciarAlunoController;
import Controller.GerenciarEstoqueController;
import Controller.GerenciarFinancaController;
import Controller.GerenciarFuncionarioController;
import Controller.GerenciarVendaController;
import Model.Academia;

public class MenuPrincipalADM extends javax.swing.JFrame {
    private Academia academia;
    
    GerenciarAlunoController controllerAluno;
    GerenciarFuncionarioController controllerFuncionario;
    GerenciarEstoqueController controllerEstoque;
    AgendamentoController controllerAgendamento;
    CatracaController controllerCatraca;
    GerenciarVendaController controllerVenda;
    GerenciarFinancaController controllerFinanca;
    
    /**
     * Creates new form MenuPrincipal
     * @param academia
     * @param controllerAluno
     * @param controllerFuncionario
     * @param controllerEstoque
     * @param controllerAgendamento
     * @param controllerCatraca
     * @param controllerVenda
     * @param controllerFinanca
     */
    public MenuPrincipalADM(Academia academia, GerenciarAlunoController controllerAluno, GerenciarFuncionarioController controllerFuncionario, GerenciarEstoqueController controllerEstoque, AgendamentoController controllerAgendamento, CatracaController controllerCatraca, GerenciarVendaController controllerVenda, GerenciarFinancaController controllerFinanca) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.academia = academia;
        this.controllerAluno = controllerAluno;
        this.controllerFuncionario = controllerFuncionario;
        this.controllerEstoque = controllerEstoque;
        this.controllerAgendamento = controllerAgendamento;
        this.controllerCatraca = controllerCatraca;
        this.controllerVenda = controllerVenda;
        this.controllerFinanca = controllerFinanca;
    }
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalADM() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.academia = null;
        this.controllerAluno = null;
        this.controllerFuncionario = null;
        this.controllerEstoque = null;
        this.controllerAgendamento = null;
        this.controllerCatraca = null;
        this.controllerVenda = null;
        this.controllerFinanca = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuAdm = new javax.swing.JMenuBar();
        jAlunos = new javax.swing.JMenu();
        jCadastrarNovoAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jAlunosCadastrados = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Academia");
        setResizable(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jAlunos.setText("Alunos");

        jCadastrarNovoAluno.setText("Cadastrar Novo Aluno");
        jCadastrarNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarNovoAlunoActionPerformed(evt);
            }
        });
        jAlunos.add(jCadastrarNovoAluno);
        jAlunos.add(jSeparator1);

        jAlunosCadastrados.setText("Alunos Cadastrados");
        jAlunosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlunosCadastradosActionPerformed(evt);
            }
        });
        jAlunos.add(jAlunosCadastrados);

        jMenuAdm.add(jAlunos);

        jMenu1.setText("Funcionários");

        jMenuItem1.setText("Cadastrar Novo Funcionário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Funcionários Cadastrados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuAdm.add(jMenu1);

        jMenu6.setText("Utilitários");

        jMenuItem4.setText("Gerenciar Estoque");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuAdm.add(jMenu6);

        jMenu7.setText("Financeiro");

        jMenuItem3.setText("Lançamentos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem3);

        jMenuAdm.add(jMenu7);

        setJMenuBar(jMenuAdm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botão da tela de cadastro de novo aluno
     * @param evt 
     */
    private void jCadastrarNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarNovoAlunoActionPerformed
        new CadastrarAluno(academia, controllerAluno).setVisible(true);
    }//GEN-LAST:event_jCadastrarNovoAlunoActionPerformed

    /**
     * Botão da tela de cadastro de novo funcionario
     * @param evt 
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new CadastrarFuncionario(academia, controllerFuncionario).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        FuncionariosCadastrados funcionariosCadastrados = new FuncionariosCadastrados(academia, controllerFuncionario);
        jDesktopPane1.add(funcionariosCadastrados);
        
        // Centralizando a view
        int x = (jDesktopPane1.getWidth() - funcionariosCadastrados.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - funcionariosCadastrados.getHeight()) / 2;
        funcionariosCadastrados.setLocation(x, y);

        funcionariosCadastrados.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jAlunosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlunosCadastradosActionPerformed
        // TODO add your handling code here:
        AlunosCadastrados alunosCadastrados = new AlunosCadastrados(academia, controllerAluno);
        jDesktopPane1.add(alunosCadastrados);
        
        // Centralizando a view
        int x = (jDesktopPane1.getWidth() - alunosCadastrados.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - alunosCadastrados.getHeight()) / 2;
        alunosCadastrados.setLocation(x, y);

        alunosCadastrados.setVisible(true);
    }//GEN-LAST:event_jAlunosCadastradosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        ProdutosCadastrados gerenciarEstoque = new ProdutosCadastrados(academia, controllerEstoque);
        jDesktopPane1.add(gerenciarEstoque);
        
        // Centralizando a view
        int x = (jDesktopPane1.getWidth() - gerenciarEstoque.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - gerenciarEstoque.getHeight()) / 2;
        gerenciarEstoque.setLocation(x, y);

        gerenciarEstoque.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Financeiro(academia, controllerFinanca).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalADM().setVisible(true);
            }
        });
    }
    
    @Override
    public String toString(){
        return "View de MenuPrincipal";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAlunos;
    private javax.swing.JMenuItem jAlunosCadastrados;
    private javax.swing.JMenuItem jCadastrarNovoAluno;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuAdm;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
