package View;

import Controller.GerenciarEstoqueController;
import Model.Academia;
import Model.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ProdutosCadastrados extends javax.swing.JInternalFrame {
    
    private Academia academia;
    
    private GerenciarEstoqueController controller;

    public ProdutosCadastrados(Academia academia, GerenciarEstoqueController controller) {
        initComponents();
        this.academia = academia;
        this.controller = controller;
        addLista(academia.getEstoque());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutosCadastrados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gerenciar Estoque");

        jTableProdutosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "Quantidade", "Valor de compra", "Valor de venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutosCadastrados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableProdutosCadastrados);

        jButton1.setText("Adicionar novo produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar produto selecionado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Deletar produto selecionado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdicionarProduto adicionarProduto = new AdicionarProduto(academia, controller);
        
        // Adicionando o WindowListener para chamar addLista ao fechar a janela
        adicionarProduto.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                // Chama o método para atualizar a lista de alunos
                addLista(academia.getEstoque());
            }
        });

        // Exibe a janela de cadastro
        adicionarProduto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = jTableProdutosCadastrados.getSelectedRow();
        
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Você não selecionou nenhum Produto");
        }else{
            String nome = jTableProdutosCadastrados.getValueAt(linhaSelecionada, 1).toString();
            String descricao = jTableProdutosCadastrados.getValueAt(linhaSelecionada, 2).toString();
            String quantidade = jTableProdutosCadastrados.getValueAt(linhaSelecionada, 3).toString();
            String valorCompra = jTableProdutosCadastrados.getValueAt(linhaSelecionada, 4).toString();
            String valorVenda = jTableProdutosCadastrados.getValueAt(linhaSelecionada, 5).toString();
            
            EditarProduto editarProduto = new EditarProduto(nome, descricao, quantidade, valorCompra, valorVenda, controller);

            // Adicionando o WindowListener para chamar addLista ao fechar a janela
            editarProduto.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                    // Chama o método para atualizar a lista de alunos
                    addLista(academia.getEstoque());
                }
            });

            // Exibe a janela de edição
            editarProduto.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = jTableProdutosCadastrados.getSelectedRow();
        
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Você não selecionou nenhum produto");
        }else{
            int resposta = JOptionPane.showConfirmDialog(
                    null,
                    "Tem certeza que deseja remover o produto?",
                    "Confirmar Remoção",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );
            
            if(resposta == JOptionPane.YES_OPTION){
                controller.removerProduto(jTableProdutosCadastrados.getValueAt(linhaSelecionada, 1).toString());
                addLista(academia.getEstoque());
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possível remover o produto!");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public JTable getjTableProdutosCadastrados() {
        return jTableProdutosCadastrados;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutosCadastrados;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que formata a lista de funcionários para a tabela
     * @param list
     */
    public void addLista(ArrayList<Produto> list){
        DefaultTableModel model = (DefaultTableModel) getjTableProdutosCadastrados().getModel();
        model.setRowCount(0);

        for (Produto produto : list) {
            Object rowData[] = new Object[6];
            rowData[0] = produto.getId();
            rowData[1] = produto.getNome();
            rowData[2] = produto.getDescricao();
            rowData[3] = produto.getQuantidade();
            rowData[4] = produto.getValorCompra();
            rowData[5] = produto.getValorVenda();
            model.addRow(rowData);
        }
    }
    
    @Override
    public String toString(){
        return "View de GerenciarEstoque";
    }
}
